-- ==============================================================================
-- SKEMA DATABASE HRIS UNTUK SUPABASE (POSTGRESQL)
-- Salin dan jalankan seluruh script ini di SQL Editor Supabase Anda
-- ==============================================================================

-- 1. FUNGSI-FUNGSI KOMPATIBILITAS (Agar fungsi T-SQL tetap berjalan normal di PostgreSQL)
CREATE OR REPLACE FUNCTION ISNULL(a anyelement, b anyelement) 
RETURNS anyelement AS $$
BEGIN
    RETURN COALESCE(a, b);
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION GETDATE() 
RETURNS timestamp without time zone AS $$
BEGIN
    RETURN CURRENT_TIMESTAMP;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION YEAR(d timestamp) 
RETURNS int AS $$
BEGIN
    RETURN EXTRACT(YEAR FROM d)::int;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION YEAR(d date) 
RETURNS int AS $$
BEGIN
    RETURN EXTRACT(YEAR FROM d)::int;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION MONTH(d timestamp) 
RETURNS int AS $$
BEGIN
    RETURN EXTRACT(MONTH FROM d)::int;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION MONTH(d date) 
RETURNS int AS $$
BEGIN
    RETURN EXTRACT(MONTH FROM d)::int;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION DATEDIFF(part text, d1 timestamp, d2 timestamp) 
RETURNS int AS $$
BEGIN
    RETURN (d2::date - d1::date)::int;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION DATEDIFF(part text, d1 date, d2 date) 
RETURNS int AS $$
BEGIN
    RETURN (d2 - d1)::int;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- 2. TABEL MASTER DEPARTEMEN & BAGIAN
CREATE TABLE IF NOT EXISTS MS_DEP (
    DEP_CD VARCHAR(20) PRIMARY KEY,
    DEP_DESC VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS MS_SEC (
    SEC_CD VARCHAR(20) PRIMARY KEY,
    SEC_DESC VARCHAR(100) NOT NULL,
    GRP_CD VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS MS_DIV (
    DIV_CD VARCHAR(20) PRIMARY KEY,
    DIV_DESC VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS MS_JOBS (
    JOB_CD VARCHAR(20) PRIMARY KEY,
    JOB_DESC VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS MSJNS_KRY (
    JNS_CODE VARCHAR(20) PRIMARY KEY,
    JNS_DESC VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Ms_Reason (
    REASON_CODE VARCHAR(20) PRIMARY KEY,
    REASON_DESC VARCHAR(100) NOT NULL,
    REASON_GROUP VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS msSHIFT (
    shift_CODE VARCHAR(20) PRIMARY KEY,
    keterangan VARCHAR(100),
    WORK_IN TIMESTAMP,
    WORK_OUT TIMESTAMP,
    STD_JAM NUMERIC(5,2) DEFAULT 8.00,
    REST1_OUT TIMESTAMP,
    REST1_IN TIMESTAMP,
    REST1 NUMERIC(5,2) DEFAULT 1.00,
    REST2_OUT TIMESTAMP,
    REST2_IN TIMESTAMP,
    REST2 NUMERIC(5,2) DEFAULT 0.00,
    MAXJAM NUMERIC(5,2) DEFAULT 13.00
);

CREATE TABLE IF NOT EXISTS MS_LIBUR_KERJA (
    TANGGAL DATE PRIMARY KEY,
    KETERANGAN VARCHAR(255) NOT NULL,
    COMPANY_CODE VARCHAR(20) DEFAULT '01',
    STATUS_LIBUR VARCHAR(10) DEFAULT '1',
    FLAG_PAY VARCHAR(10) DEFAULT '1'
);

-- 3. TABEL DATA KARYAWAN
CREATE TABLE IF NOT EXISTS EMP_TABLE (
    EMP_CD VARCHAR(30) PRIMARY KEY,
    EMP_NM VARCHAR(100) NOT NULL,
    DEP_CD VARCHAR(20),
    SEC_CD VARCHAR(20),
    JOB_CD VARCHAR(20),
    DIV_CD VARCHAR(20),
    OUT_CD VARCHAR(20),
    JNS_KRY VARCHAR(20),
    Act_NonAct BOOLEAN DEFAULT TRUE,
    DT_ENTRY DATE,
    DT_RSG DATE,
    DT_PROB DATE,
    DT_BRT DATE,
    PLC_BRT VARCHAR(100),
    ADRR TEXT,
    CT VARCHAR(50),
    SX VARCHAR(5),
    NPWP VARCHAR(50),
    PTKP_ST VARCHAR(20),
    noktp VARCHAR(50),
    agama VARCHAR(50),
    telepon VARCHAR(50),
    ACC_NO VARCHAR(50),
    Status_Pekerjaan VARCHAR(50),
    IMG_NM VARCHAR(255),
    FLAG_OT VARCHAR(10) DEFAULT '1',
    ALL_IN VARCHAR(10) DEFAULT '0',
    SPSI_NO VARCHAR(50),
    No_Reg VARCHAR(50),
    BS_SLR NUMERIC(15,2) DEFAULT 0,
    Company_Code VARCHAR(20) DEFAULT '01'
);

-- 4. TABEL TRANSAKSI PRESENSI & ABSENSI
CREATE TABLE IF NOT EXISTS TR_ABSEN (
    DATE_TRANS DATE NOT NULL,
    EMP_CD VARCHAR(30) NOT NULL,
    EMP_NM VARCHAR(100),
    SEC_CD VARCHAR(20),
    SHIFT VARCHAR(20) DEFAULT '1',
    STATUS_HARI VARCHAR(50) DEFAULT 'KERJA',
    DATE_IN TIMESTAMP,
    WORK_IN TIMESTAMP,
    WORK_IN1 TIMESTAMP,
    DATE_OUT TIMESTAMP,
    WORK_OUT TIMESTAMP,
    WORK_OUT1 TIMESTAMP,
    JAM_MASUK VARCHAR(20),
    JAM_PULANG VARCHAR(20),
    JAM_KERJA NUMERIC(6,2) DEFAULT 0,
    REASON VARCHAR(20),
    OT_1 NUMERIC(6,2) DEFAULT 0,
    OT_2 NUMERIC(6,2) DEFAULT 0,
    OT_3 NUMERIC(6,2) DEFAULT 0,
    OT_4 NUMERIC(6,2) DEFAULT 0,
    T_OT NUMERIC(15,2) DEFAULT 0,
    Time_Late NUMERIC(6,2) DEFAULT 0,
    U_MAKAN NUMERIC(12,2) DEFAULT 0,
    U_TRANSPORT NUMERIC(12,2) DEFAULT 0,
    PRIMARY KEY (EMP_CD, DATE_TRANS)
);

-- 5. TABEL CUTI & IZIN
CREATE TABLE IF NOT EXISTS tblCUTI (
    id SERIAL PRIMARY KEY,
    EMP_CD VARCHAR(30) NOT NULL,
    EMP_NM VARCHAR(100),
    AWAL_CUTI DATE NOT NULL,
    AKHIR_CUTI DATE NOT NULL,
    REASON VARCHAR(20),
    REMARK VARCHAR(255),
    LM_CUTI INT DEFAULT 1,
    HR_MG INT DEFAULT 0,
    HR_LBR INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS tbldetcuti (
    id SERIAL PRIMARY KEY,
    EMP_CD VARCHAR(30) NOT NULL,
    EMP_NM VARCHAR(100),
    TGL_CUTI DATE NOT NULL,
    REASON VARCHAR(20),
    UNIQUE (EMP_CD, TGL_CUTI)
);

-- 6. TABEL LEMBUR ALL-IN & SPL
CREATE TABLE IF NOT EXISTS TR_LEMBUR_ALLIN (
    id SERIAL PRIMARY KEY,
    DATE_TRANS DATE NOT NULL,
    EMP_CD VARCHAR(30) NOT NULL,
    JAM_MULAI VARCHAR(10) NOT NULL,
    JAM_SELESAI VARCHAR(10) NOT NULL,
    NOMINAL NUMERIC(15,2) NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS TR_SPL_PLAN (
    id SERIAL PRIMARY KEY,
    DATE_TRANS DATE NOT NULL,
    LINE_ID VARCHAR(50),
    JOB_DESC VARCHAR(100),
    JAM_17_OPR INT DEFAULT 0,
    JAM_18_OPR INT DEFAULT 0,
    JAM_19_OPR INT DEFAULT 0,
    JAM_20_OPR INT DEFAULT 0,
    STATUS_DOC VARCHAR(50) DEFAULT 'APPROVED'
);

-- 7. INDEX UNTUK PERFORMA CEPAT (HIGH PERFORMANCE)
CREATE INDEX IF NOT EXISTS idx_tr_absen_date ON TR_ABSEN(DATE_TRANS);
CREATE INDEX IF NOT EXISTS idx_tr_absen_emp ON TR_ABSEN(EMP_CD);
CREATE INDEX IF NOT EXISTS idx_tr_absen_sec ON TR_ABSEN(SEC_CD);
CREATE INDEX IF NOT EXISTS idx_emp_table_sec ON EMP_TABLE(SEC_CD);
CREATE INDEX IF NOT EXISTS idx_emp_table_dep ON EMP_TABLE(DEP_CD);
CREATE INDEX IF NOT EXISTS idx_emp_table_act ON EMP_TABLE(Act_NonAct);
CREATE INDEX IF NOT EXISTS idx_tbldetcuti_emp_tgl ON tbldetcuti(EMP_CD, TGL_CUTI);
CREATE INDEX IF NOT EXISTS idx_tblcuti_emp ON tblCUTI(EMP_CD);
